[tool.poetry]
name = "ujuc.github.io"
version = "2.0.0"
description = "blog"
authors = ["Sungjin Kang <ujuc@ujuc.me>"]

packages = [
    { include='cli', from='.' }
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
pendulum = "^2.1.2"
pelican = "^4.8.0"
Markdown = "^3.4.1"
rich = "^13.2.0"
cleo = "^2.0.1"

[tool.poetry.scripts]
cli = 'cli.main:run'

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
isort = "^5.11.4"
ruff = "^0.0.260"

[tool.isort]
profile = "black"
force_single_line = true
atomic = true
lines_after_imports = 2
lines_between_types = 1
src_paths = [
    "cli"
]

[tool.ruff]
select = ["E", "F"]

exclude = [
    ".git",
    ".venv",
    "__pycache__",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
