[tool.poetry]
name = "ujuc.github.io"
version = "1.1.0"
description = "blog"
authors = ["Thomas SJ Kang <ujuc@ujuc.kr>"]

packages = [
    { include='cli', from='.' }
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
ghp-import = "^0.5.5"
pendulum = "^2.0.5"
pelican = "^4.2.0"
Markdown = "^3.1.1"
black = "==20.08b1"
invoke = "^1.3.0"
rich = "^10.6.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
cli = 'cli.main:run'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
