[tool.poetry]
name = "ujuc.github.io"
version = "1.1.0"
description = "blog"
authors = ["Sungjin Kang <ujuc@ujuc.me>"]

packages = [
    { include='cli', from='.' }
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
ghp-import = "^2.0.2"
pendulum = "^2.1.2"
pelican = "^4.7.1"
Markdown = "^3.3.6"
black = "^21.12b0"
invoke = "^1.6.0"
rich = "^10.16.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
cli = 'cli.main:run'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
