[project]
name = "ujuc.github.io"
version = "2.0.0"
description = "blog"
readme = "README.md"
requires-python = ">= 3.13"
authors = [{ name = "sungjin.kang", email = "ujuc@ujuc.me" }]
dependencies = [
  "cleo>=2.1.0",
  "markdown-mermaidjs>=2.0.0",
  "markdown>=3.8",
  "pelican-seo>=1.4.0",
  "pelican>=4.11.0",
  "pendulum>=3.1.0",
  "rich>=14.0.0",
]

[project.scripts]
cli = "cli.main:run"

[dependency-groups]
dev = [
  "pre-commit>=4.2.0",
  "ruff>=0.12.5",
  "ty>=0.0.1a16",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["cli"]

[tool.rye]
managed = true
dev-dependencies = []
