[tool.poetry]
name = "ujuc.github.io"
version = "1.1.0"
description = "blog"
authors = ["Sungjin Kang <ujuc@ujuc.me>"]

packages = [
    { include='cli', from='.' }
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
ghp-import = "^2.1.0"
pendulum = "^2.1.2"
pelican = "^4.8.0"
Markdown = "^3.4.1"
black = "^22.10.0"
invoke = "^1.7.3"
rich = "^12.6.0"
cleo = "^2.0.1"
isort = "^5.11.4"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
cli = 'cli.main:run'

[tool.isort]
profile = "black"
force_single_line = true
atomic = true
lines_after_imports = 2
lines_between_types = 1
src_paths = [
    "cli"
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
