name: github pages

on:
  push:
    branches: develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule update --init --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          check-latest: true

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8
 
      - name: Install python pacakge
        run: poetry install

      - name: Build posts
        run: poetry run cli build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.1
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: master
          publish_dir: ./output
          user_name: Sungjin Kang
          user_email: ujuc@ujuc.me
