name: github pages

on:
  push:
    branches: develop

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.1

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.2.1

      - name: Install python pacakge
        run: poetry install

      - name: Build posts
        run: poetry run cli build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: master
          publish_dir: ./output
          user_name: Sunjin Kang
          user_email: ujuc@ujuc.me
