name: Publish

on:
  push:
    branches:
    - develop

jobs:
  build:
    name: Build Blog
    runs-on: ubuntu-latest

    steps:
    - name: Fixe up git URLs
      run: echo -e '[url "https://ujuc@github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Setup python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install packages
      run: |
        pip install -U pip
        pip install poetry
        poetry install
    - name: Publish blog
      run: |
        poetry run cli pub

