name: Publish

on:
  push:
    branches:
    - develop

jobs:
  build:
    name: Build Blog
    runs-on: ubuntu-latest

    steps:
    - name: Checkout datas
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Setup python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install packages
      run: |
        pip install -U pip
        pip install poetry
        poetry install
    - name: Publish blog
      run: |
        poetry run cli pub

